import { useState } from 'react';
import { useDoctorAuth } from '@/hooks/useDoctorAuth';
import { useDoctorDashboardI18n } from '@/hooks/useDoctorDashboardI18n';
import { useTheme } from '@/hooks/useTheme';
import { useLanguage } from '@/hooks/useLanguage';
import { doctorProfileImageService } from '@/services/doctorProfileImage.service';
import { DoctorIcon } from '@/components/doctor/DoctorIcon';

const appointments = [
  { id:'a1', time:'10:00 AM', patient:'Rohan Das', type:'Follow-up', mode:'Online', status:'Upcoming', age:'28', gender:'Male', reason:'Fever and cough', doctor:'Dr. Arjun Sharma' },
  { id:'a2', time:'11:30 AM', patient:'Priya Sen', type:'First Visit', mode:'In Clinic', status:'Upcoming', age:'32', gender:'Female', reason:'Gastritis', doctor:'Dr. Arjun Sharma' },
  { id:'a3', time:'02:00 PM', patient:'Amit Verma', type:'Follow-up', mode:'In Clinic', status:'Upcoming', age:'45', gender:'Male', reason:'Back pain', doctor:'Dr. Arjun Sharma' },
  { id:'a4', time:'04:00 PM', patient:'Sneha Roy', type:'Report Discussion', mode:'Online', status:'Upcoming', age:'26', gender:'Female', reason:'Skin allergy', doctor:'Dr. Arjun Sharma' },
  { id:'a5', time:'05:30 PM', patient:'Karan Mehta', type:'First Visit', mode:'Online', status:'Pending', age:'38', gender:'Male', reason:'Hypertension', doctor:'Dr. Arjun Sharma' },
  { id:'a6', time:'06:30 PM', patient:'Neha Gupta', type:'Follow-up', mode:'In Clinic', status:'Pending', age:'29', gender:'Female', reason:'Diabetes follow-up', doctor:'Dr. Arjun Sharma' },
];
const patients = appointments.map((a,i)=>({ id:`P-${String(i+1).padStart(3,'0')}`, name:a.patient, age:a.age, gender:a.gender, lastVisit:['10 Oct 2026','08 Oct 2026','05 Oct 2026','02 Oct 2026','30 Sep 2026','28 Sep 2026'][i], status:i===4?'Inactive':'Active' }));
const prescriptions = appointments.slice(0,5).map((a,i)=>({ patient:a.patient, date:['10 Oct 2026','08 Oct 2026','05 Oct 2026','03 Oct 2026','30 Sep 2026'][i], diagnosis:['Viral Infection','Gastritis','Back Pain','Skin Allergy','Hypertension'][i], medicines:[3,4,3,2,4][i] }));
const records = [
  { name:'Blood_Report.pdf', type:'Blood Report', date:'03 Oct 2026', size:'2.4 MB' },
  { name:'XRay_Chest.jpg', type:'X-Ray Report', date:'20 Sep 2026', size:'1.8 MB' },
  { name:'Prescription_Priya.pdf', type:'Prescription', date:'08 Oct 2026', size:'1.2 MB' },
  { name:'Lab_Test.pdf', type:'Lab Report', date:'01 Aug 2026', size:'3.1 MB' },
];

function initials(name: string) { return name.split(' ').map(v=>v[0]).slice(0,2).join('').toUpperCase(); }
function PageHead({ title, subtitle, action }: { title:string; subtitle:string; action?:React.ReactNode }) { return <div className="doctor-page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
function Button({ children, onClick, variant='primary' }: {children:React.ReactNode; onClick?:()=>void; variant?:'primary'|'soft'|'ghost'}) { return <button className={`doctor-btn doctor-btn--${variant}`} onClick={onClick}>{children}</button>; }
function Status({ value }: { value:string }) { return <span className={`doctor-status doctor-status--${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>; }
function Avatar({ name, src }: {name:string; src?:string|null}) { return src ? <img className="doctor-table-avatar" src={src} alt=""/> : <div className="doctor-table-avatar doctor-table-avatar--initials">{initials(name)}</div>; }
function TableCard({ children, className='' }: {children:React.ReactNode; className?:string}) { return <div className={`doctor-card doctor-table-card ${className}`}>{children}</div>; }

export function DoctorOverview() {
  const t=useDoctorDashboardI18n(); const { doctor }=useDoctorAuth(); const avatar=doctorProfileImageService.get();
  return <div className="doctor-page">
    <section className="doctor-welcome"><div><span className="doctor-eyebrow">MediMitra • {t.overview}</span><h1>{t.goodMorning}, {doctor?.title ?? 'Dr.'} {doctor?.first_name ?? 'Arjun'}!</h1><p>{t.welcome}</p></div><div className="doctor-welcome-art"><DoctorIcon name="stethoscope" size={54}/></div></section>
    <section className="doctor-stat-grid">
      {[['totalPatients','124','+12 '+t.thisMonth,'blue','users'],['todayAppointments','8','3 '+t.completed,'teal','calendar'],['pendingRequests','5','10 '+t.pending,'orange','clock'],['totalPrescriptions','38','+6 '+t.thisWeek,'purple','prescription']].map(([k,v,f,c,icon])=><div className="doctor-stat-card" key={k}><div className={`doctor-stat-icon ${c}`}><DoctorIcon name={icon as any}/></div><div><span>{t[k as keyof typeof t]}</span><strong>{v}</strong><small>{f}</small></div></div>)}
    </section>
    <div className="doctor-two-column">
      <TableCard><div className="doctor-card-head"><div><h2>{t.todaysAppointments}</h2><p>{t.recent}</p></div><Button variant="ghost">{t.viewAll} <DoctorIcon name="arrow" size={14}/></Button></div><div className="doctor-list">{appointments.slice(0,4).map(a=><div className="doctor-list-row" key={a.id}><Avatar name={a.patient}/><div className="doctor-list-main"><strong>{a.patient}</strong><span>{a.reason}</span></div><span className="doctor-list-time">{a.time}</span><span className="doctor-mode">{a.mode}</span><Button variant="soft">{t.consult}</Button></div>)}</div></TableCard>
      <TableCard><div className="doctor-card-head"><div><h2>{t.recentPatients}</h2><p>{t.recent}</p></div><Button variant="ghost">{t.viewAll} <DoctorIcon name="arrow" size={14}/></Button></div><div className="doctor-list">{patients.slice(0,5).map(p=><div className="doctor-list-row" key={p.id}><Avatar name={p.name}/><div className="doctor-list-main"><strong>{p.name}</strong><span>{p.age} / {p.gender}</span></div><Status value={p.status}/><Button variant="soft">{t.view}</Button></div>)}</div></TableCard>
    </div>
  </div>;
}

export function DoctorAppointments() {
  const t=useDoctorDashboardI18n(); const [tab,setTab]=useState('Upcoming');
  const filtered=tab==='Upcoming'?appointments:tab==='Pending'?appointments.slice(4):tab==='Completed'?appointments.slice(0,2):appointments.slice(0,0);
  return <div className="doctor-page"><PageHead title={t.appointments} subtitle={t.welcome}/><div className="doctor-tabs">{['Upcoming','Pending','Completed','Cancelled'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='Upcoming'?t.upcoming:x==='Pending'?t.pendingTab:x==='Completed'?t.completed:t.cancelled} <span>{x==='Upcoming'?2:x==='Pending'?1:x==='Completed'?3:0}</span></button>)}</div><TableCard><div className="doctor-toolbar"><div className="doctor-date-control">03 Oct 2026 <DoctorIcon name="calendar" size={15}/></div><div className="doctor-segment"><button className="active">{t.day}</button><button>{t.week}</button><button>{t.month}</button></div></div><div className="doctor-data-table"><div className="doctor-data-row doctor-data-head"><span>{t.date}</span><span>{t.name}</span><span>{t.type}</span><span>{'Mode'}</span><span>{t.status}</span><span>{t.action}</span></div>{filtered.map(a=><div className="doctor-data-row" key={a.id}><span>{a.time}</span><span className="person-cell"><Avatar name={a.patient}/><b>{a.patient}</b></span><span>{a.type}</span><span>{a.mode}</span><span><Status value={a.status}/></span><span><Button variant="soft">{a.status==='Upcoming'?t.start:t.view}</Button></span></div>)}</div></TableCard></div>;
}

export function DoctorPatients() {
  const t=useDoctorDashboardI18n(); const [query,setQuery]=useState(''); const filtered=patients.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||p.id.toLowerCase().includes(query.toLowerCase()));
  return <div className="doctor-page"><PageHead title={t.patients} subtitle="View and manage your patients." action={<Button><DoctorIcon name="plus" size={15}/> {t.addPatient}</Button>}/><TableCard><div className="doctor-toolbar"><div className="doctor-search doctor-search--inside"><DoctorIcon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.patientSearch}/></div><Button variant="ghost"><DoctorIcon name="filter" size={15}/>{t.filter}</Button></div><div className="doctor-data-table"><div className="doctor-data-row doctor-data-head"><span>{t.id}</span><span>{t.name}</span><span>{t.ageGender}</span><span>{t.lastVisit}</span><span>{t.status}</span><span>{t.action}</span></div>{filtered.map(p=><div className="doctor-data-row" key={p.id}><span>{p.id}</span><span className="person-cell"><Avatar name={p.name}/><b>{p.name}</b></span><span>{p.age} / {p.gender}</span><span>{p.lastVisit}</span><span><Status value={p.status}/></span><span><Button variant="soft">{t.view}</Button></span></div>)}</div></TableCard></div>;
}

export function DoctorSchedule() {
  const t=useDoctorDashboardI18n(); const slots=['10:00 AM - 11:00 AM','11:30 AM - 12:30 PM','02:00 PM - 03:00 PM','04:00 PM - 05:00 PM','05:30 PM - 06:30 PM'];
  return <div className="doctor-page"><PageHead title={t.schedule} subtitle={t.manageSchedule}/><div className="schedule-grid"><TableCard><div className="doctor-card-head"><h2>October 2026</h2><span className="doctor-muted">Sun · Mon · Tue · Wed · Thu · Fri · Sat</span></div><div className="calendar-grid">{['28','29','30','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'].map((d,i)=><span className={d==='10'?'selected':''} key={`${d}-${i}`}>{d}</span>)}</div></TableCard><TableCard><div className="doctor-card-head"><div><h2>{t.availableSlots}</h2><p>{t.today}</p></div></div><div className="slot-list">{slots.map(s=><div className="slot-row" key={s}><span>{s}</span><label className="doctor-switch"><input type="checkbox" defaultChecked/><i/></label></div>)}<Button><DoctorIcon name="plus" size={15}/>{t.addSlot}</Button></div></TableCard></div></div>;
}

export function DoctorConsultations() {
  const t=useDoctorDashboardI18n(); const [selected,setSelected]=useState(appointments[0]);
  return <div className="doctor-page"><PageHead title={t.consultations} subtitle="Review patients, notes and consultation details."/><div className="consultation-layout"><TableCard><div className="doctor-list doctor-list--patients">{appointments.slice(0,4).map(a=><button className={`consult-patient ${selected.id===a.id?'active':''}`} key={a.id} onClick={()=>setSelected(a)}><Avatar name={a.patient}/><span><b>{a.patient}</b><small>{a.time} · {a.mode}</small></span></button>)}</div></TableCard><TableCard><div className="consult-profile"><Avatar name={selected.patient}/><div><h2>{selected.patient}</h2><p>{selected.age} years · {selected.gender}</p></div><Button variant="soft">{t.viewHistory}</Button></div><div className="doctor-tabs doctor-tabs--small"><button className="active">{t.notes}</button><button>{t.prescriptions}</button><button>{t.followUp}</button><button>{t.documents}</button></div><label className="field-label">{t.chiefComplaint}<textarea defaultValue={selected.reason}/></label><label className="field-label">{t.diagnosis}<input defaultValue="Viral Infection (Suspected)"/></label><label className="field-label">{t.notes}<textarea placeholder="Add clinical notes..."/></label><div className="doctor-form-actions"><Button>{t.saveNotes}</Button></div></TableCard></div></div>;
}

export function DoctorPrescriptions() { const t=useDoctorDashboardI18n(); return <div className="doctor-page"><PageHead title={t.prescriptions} subtitle="Create and manage prescriptions." action={<Button><DoctorIcon name="plus" size={15}/>{t.newPrescription}</Button>}/><TableCard><div className="doctor-toolbar"><div className="doctor-search doctor-search--inside"><DoctorIcon name="search" size={16}/><input placeholder={t.prescriptionSearch}/></div><div className="doctor-segment"><button className="active">{t.all}</button><button>{t.today}</button><button>{t.thisWeek}</button><button>This Month</button></div></div><div className="doctor-data-table"><div className="doctor-data-row doctor-data-head"><span>{t.name}</span><span>{t.date}</span><span>Diagnosis</span><span>{t.medicines}</span><span>{t.action}</span></div>{prescriptions.map(p=><div className="doctor-data-row" key={p.patient}><span className="person-cell"><Avatar name={p.patient}/><b>{p.patient}</b></span><span>{p.date}</span><span>{p.diagnosis}</span><span>{p.medicines} medicines</span><span><Button variant="soft">{t.view}</Button></span></div>)}</div></TableCard></div>; }

export function DoctorRecords() { const t=useDoctorDashboardI18n(); return <div className="doctor-page"><PageHead title={t.medicalRecords} subtitle="Review and manage patient medical documents." action={<Button><DoctorIcon name="plus" size={15}/>{t.upload}</Button>}/><div className="record-tabs">{[t.all,t.prescriptions,t.reports,t.notesTab,t.others].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="record-grid">{records.map((r,i)=><div className="doctor-card record-card" key={r.name}><div className={`record-icon record-icon--${i%3}`}><DoctorIcon name="document"/></div><div><strong>{r.name}</strong><span>{r.type}</span><small>{r.date} · {r.size}</small></div><Button variant="soft">{t.view}</Button></div>)}</div></div>; }

export function DoctorEarnings() { const t=useDoctorDashboardI18n(); const bars=[40,55,48,70,62,78,65,86,74,95,88,100]; return <div className="doctor-page"><PageHead title={t.earningsReports} subtitle="Track your consultation and earnings statistics."/><div className="doctor-stat-grid doctor-stat-grid--4">{[[t.totalEarnings,'₹48,500','+12%'],[t.totalConsultations,'56','+8%'],[t.onlineConsultations,'22','39%'],[t.inClinicConsultations,'34','61%']].map((s,i)=><div className="doctor-stat-card" key={s[0]}><div className={`doctor-stat-icon ${['teal','blue','purple','orange'][i]}`}><DoctorIcon name={i===0?'wallet':i===1?'stethoscope':'calendar'}/></div><div><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small></div></div>)}</div><div className="earnings-grid"><TableCard><div className="doctor-card-head"><h2>{t.earningsOverview}</h2><span className="doctor-muted">Oct 2026</span></div><div className="fake-chart">{bars.map((h,i)=><div key={i} style={{height:`${h}%`}}><span>{i+1}</span></div>)}</div></TableCard><TableCard><div className="doctor-card-head"><h2>{t.consultationTypes}</h2></div><div className="donut"><div><strong>56</strong><span>Total</span></div></div><div className="legend"><span><i/>Online · 22 (39%)</span><span><i/>In-clinic · 34 (61%)</span></div></TableCard></div></div>; }

export function DoctorProfile() { const t=useDoctorDashboardI18n(); const {doctor}=useDoctorAuth(); const avatar=doctorProfileImageService.get(); const name=doctor?`${doctor.title} ${doctor.first_name} ${doctor.last_name}`:'Dr. Arjun Sharma'; return <div className="doctor-page"><PageHead title={t.myProfile} subtitle="View and manage your professional information." action={<Button variant="soft"><DoctorIcon name="edit" size={15}/>{t.editProfile}</Button>}/><div className="profile-grid"><TableCard><div className="profile-photo-wrap">{avatar?<img src={avatar} alt=""/>:<div className="profile-photo-placeholder">{initials(name)}</div>}<Button variant="soft">{t.changePhoto}</Button><h2>{name}</h2><p>{doctor?.specialization || 'Internal Medicine'}</p><span className="verified-badge"><DoctorIcon name="check" size={13}/>{t.verified}</span></div></TableCard><TableCard><h2>{t.professionalInfo}</h2><div className="detail-grid"><Detail label="Full Name" value={name}/><Detail label="Date of Birth" value="15 Mar 1988"/><Detail label="Phone" value={doctor?.phone || '+91 9876543210'}/><Detail label="Email" value={doctor?.email || 'doctor@medimitra.example'}/><Detail label="Clinic Address" value={doctor?.chambers?.[0]?.address || 'Apollo Clinic, Kolkata'}/><Detail label={t.registration} value="WB-123456"/><Detail label="Experience" value="8 years"/></div></TableCard></div></div>; }
function Detail({label,value}:{label:string;value:string}){return <div className="detail-item"><span>{label}</span><strong>{value}</strong></div>}

export function DoctorSettings() { const t=useDoctorDashboardI18n(); const {theme,setTheme}=useTheme(); const {language,setLanguage}=useLanguage(); return <div className="doctor-page"><PageHead title={t.settings} subtitle="Manage your account preferences."/><div className="settings-grid"><TableCard><h2>{t.appearance}</h2><div className="option-row"><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}><DoctorIcon name="sun"/> {t.light}</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}><DoctorIcon name="moon"/> {t.dark}</button><button className={theme!=='light'&&theme!=='dark'?'selected':''} onClick={()=>setTheme('light')}><DoctorIcon name="settings"/> {t.system}</button></div></TableCard><TableCard><h2>{t.language}</h2><div className="option-row"><button className={language==='en'?'selected':''} onClick={()=>setLanguage('en')}>🇬🇧 {t.english}</button><button className={language==='bn'?'selected':''} onClick={()=>setLanguage('bn')}>🇧🇩 {t.bengali}</button><button className={language==='hi'?'selected':''} onClick={()=>setLanguage('hi')}>🇮🇳 {t.hindi}</button></div></TableCard><TableCard><h2>{t.notificationsSettings}</h2><Toggle label={t.emailNotifications}/><Toggle label={t.appointmentAlerts}/><Toggle label={t.newPatientRequests}/></TableCard><TableCard><h2>{t.security}</h2><Button variant="soft">{t.changePassword}</Button><Toggle label={t.twoFactor}/></TableCard><TableCard><h2>{t.account}</h2><Button variant="soft">{t.deleteAccount}</Button></TableCard></div></div>; }
function Toggle({label}:{label:string}){return <label className="setting-toggle"><span>{label}</span><input type="checkbox" defaultChecked/><i/></label>}

export function DoctorAIAssistant(){ const t=useDoctorDashboardI18n(); const [messages,setMessages]=useState<{r:'ai'|'user';t:string}[]>([{r:'ai',t:t.hello}]); const [value,setValue]=useState(''); const send=()=>{if(!value.trim())return;setMessages(m=>[...m,{r:'user',t:value},{r:'ai',t:t.aiReply}]);setValue('')}; return <div className="doctor-page"><PageHead title={t.aiTitle} subtitle={t.aiSubtitle}/><div className="doctor-ai-page"><div className="doctor-ai-page-head"><div className="doctor-ai-orb"><DoctorIcon name="bot" size={28}/></div><div><h2>MediMitra AI</h2><p>{t.aiComing}</p></div></div><div className="doctor-ai-page-body">{messages.map((m,i)=><div className={`ai-page-message ${m.r==='user'?'user':''}`} key={i}>{m.t}</div>)}</div><div className="doctor-ai-page-input"><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={t.typeMessage}/><Button onClick={send}>{t.send}</Button></div></div></div>; }
