import { useMemo, useState } from 'react';
import { AdminIcon } from './AdminIcon';
import { RemoveAccountModal } from './RemoveAccountModal';
import { useAdminDashboardI18n } from '@/hooks/useAdminDashboardI18n';
import type { DoctorAccount, PatientAccount } from '@/pages/admin/adminData';

type Props = { kind:'patient'|'doctor'; rows: PatientAccount[]|DoctorAccount[]; onRemove:(id:string)=>void; compact?:boolean };
export function AccountTable({kind,rows,onRemove,compact=false}:Props){
 const t=useAdminDashboardI18n(); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'all'|'active'|'inactive'>('all'); const [confirm,setConfirm]=useState<{id:string,name:string}|null>(null);
 const filtered=useMemo(()=>rows.filter(r=>{const q=query.toLowerCase(); const match=!q || r.name.toLowerCase().includes(q)||r.email.toLowerCase().includes(q)||r.phone.includes(q)||('specialization' in r && r.specialization.toLowerCase().includes(q)); return match&&(status==='all'||r.status===status);}),[rows,query,status]);
 const patient=kind==='patient';
 return <section className="admin-panel"><div className="admin-panel-head"><div><div className="admin-panel-title"><span className={`admin-panel-icon ${patient?'blue':'purple'}`}><AdminIcon name={patient?'patients':'doctors'}/></span><div><h2>{patient?t.patientAccounts:t.doctorAccounts}</h2><p>{patient?t.patientAccountsDesc:t.doctorAccountsDesc}</p></div></div></div><div className="admin-table-tools"><div className="admin-table-search"><AdminIcon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={patient?t.searchPatients:t.searchDoctors}/></div><div className="admin-filter"><AdminIcon name="filter" size={15}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">{patient?t.allPatients:t.allDoctors}</option><option value="active">{t.active}</option><option value="inactive">{t.inactive}</option></select></div></div></div>
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>#</th><th>{t.id}</th><th>{t.name}</th>{patient?<><th>{t.email}</th><th>{t.phone}</th><th>{t.gender}</th><th>{t.age}</th></>:<><th>{t.specialization}</th><th>{t.email}</th><th>{t.phone}</th><th>{t.experience}</th></>}<th>{t.registered}</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><span className="admin-id">{r.id}</span></td><td><strong>{r.name}</strong></td>{patient?<><td>{r.email}</td><td>{r.phone}</td><td><span className={`gender ${r.gender.toLowerCase()}`}>{r.gender}</span></td><td>{r.age}</td></>:<><td><span className="specialization">{r.specialization}</span></td><td>{r.email}</td><td>{r.phone}</td><td>{r.experience} {t.years}</td></>}<td>{r.registered}</td><td><span className={`status-dot ${r.status}`}>{r.status==='active'?t.active:t.inactive}</span></td><td><div className="admin-row-actions"><button className="admin-remove-btn" onClick={()=>setConfirm({id:r.id,name:r.name})}><AdminIcon name="trash" size={15}/>{t.remove}</button><button className="admin-more" title={t.view}>⋮</button></div></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="admin-empty">{t.noResults}</div>}<div className="admin-table-footer"><span>{t.showing} {filtered.length} {t.of} {rows.length} {t.accounts}</span><div className="pagination"><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>…</button><button>›</button></div></div>{confirm&&<RemoveAccountModal name={confirm.name} onCancel={()=>setConfirm(null)} onConfirm={()=>{onRemove(confirm.id);setConfirm(null)}}/>}</section>
}
