import type { LanguageCode } from '@/types';

type Dict = typeof en;

const en = {
  overview:'Overview', appointments:'Appointments', patients:'Patients', schedule:'My Schedule', consultations:'Consultations', prescriptions:'Prescriptions', records:'Medical Records', earnings:'Earnings', profile:'Profile', settings:'Settings', ai:'AI Assistant', logout:'Logout',
  search:'Search patients, appointments...', notifications:'Notifications', type:'Type', goodMorning:'Good Morning', welcome:'Here’s your practice overview. Help patients with better, smarter care.', totalPatients:'Total Patients', todayAppointments:'Today’s Appointments', pendingRequests:'Pending Requests', totalPrescriptions:'Total Prescriptions', thisMonth:'this month', completed:'completed', pending:'pending', thisWeek:'this week', today:'Today', recentPatients:'Recent Patients', todaysAppointments:'Today’s Appointments', viewAll:'View All', start:'Start', view:'View', consult:'Consult', upcoming:'Upcoming', confirmed:'Confirmed', online:'Online', inClinic:'In Clinic', followUp:'Follow-up', firstVisit:'First Visit', reportDiscussion:'Report Discussion', recent:'Recent', noData:'No data available yet', connectBackend:'Connect the doctor dashboard API to display live data.', aiAsk:'Ask MediMitra AI', aiComing:'Your clinical AI assistant is ready for the interface. Backend/RAG integration can be connected next.',
  filter:'Filter', addPatient:'Add Patient', patientSearch:'Search patients by name, phone or ID...', status:'Status', action:'Action', active:'Active', inactive:'Inactive', id:'ID', name:'Name', ageGender:'Age / Gender', lastVisit:'Last Visit',
  pendingTab:'Pending', cancelled:'Cancelled', day:'Day', week:'Week', month:'Month', addSlot:'Add Slot', availableSlots:'Available Time Slots', manageSchedule:'Manage your availability and consultation schedule.',
  history:'History', notes:'Notes', chiefComplaint:'Chief Complaint', diagnosis:'Diagnosis (Optional)', saveNotes:'Save Notes', viewHistory:'View History', documents:'Documents',
  newPrescription:'New Prescription', prescriptionSearch:'Search prescriptions...', all:'All', date:'Date', medicines:'Medicines',
  medicalRecords:'Medical Records', reports:'Reports', notesTab:'Notes', others:'Others', upload:'Upload',
  earningsReports:'Earnings & Reports', totalEarnings:'Total Earnings', totalConsultations:'Total Consultations', onlineConsultations:'Online Consultations', inClinicConsultations:'In-Clinic Consultations', earningsOverview:'Earnings Overview', consultationTypes:'Consultation Types',
  myProfile:'My Profile', professionalInfo:'Professional Information', contactInfo:'Contact Information', changePhoto:'Change Photo', editProfile:'Edit Profile', verified:'Verified', registration:'Registration No.', clinicAddress:'Clinic Address', experience:'Experience',
  appearance:'Appearance', light:'Light', dark:'Dark', system:'System', language:'Language', english:'English', bengali:'বাংলা', hindi:'हिन्दी', notificationsSettings:'Notifications', emailNotifications:'Email Notifications', appointmentAlerts:'Appointment Alerts', newPatientRequests:'New Patient Requests', security:'Security', changePassword:'Change Password', twoFactor:'Two-Factor Authentication', account:'Account', deleteAccount:'Delete Account',
  aiTitle:'MediMitra AI Assistant', aiSubtitle:'Your professional health assistant.', hello:'Hello! I’m MediMitra AI. How can I help you today?', showPending:'Show today’s pending appointments.', aiReply:'You have 5 pending appointments today. I can also summarize patient history, organize notes, and help prepare consultation drafts.', typeMessage:'Type your message...', send:'Send',
  noDoctor:'Doctor', notAvailable:'Not available', menu:'Menu', close:'Close',
};

const bn: Dict = {
  overview:'ওভারভিউ', appointments:'অ্যাপয়েন্টমেন্ট', patients:'রোগী', schedule:'আমার সময়সূচি', consultations:'পরামর্শ', prescriptions:'প্রেসক্রিপশন', records:'মেডিকেল রেকর্ড', earnings:'আয়', profile:'প্রোফাইল', settings:'সেটিংস', ai:'এআই সহকারী', logout:'লগআউট',
  search:'রোগী, অ্যাপয়েন্টমেন্ট খুঁজুন...', notifications:'নোটিফিকেশন', type:'ধরন', goodMorning:'সুপ্রভাত', welcome:'আপনার প্র্যাকটিসের সারাংশ দেখুন এবং আরও ভালো ও স্মার্ট কেয়ার দিন।', totalPatients:'মোট রোগী', todayAppointments:'আজকের অ্যাপয়েন্টমেন্ট', pendingRequests:'অপেক্ষমাণ অনুরোধ', totalPrescriptions:'মোট প্রেসক্রিপশন', thisMonth:'এই মাসে', completed:'সম্পন্ন', pending:'অপেক্ষমাণ', thisWeek:'এই সপ্তাহে', today:'আজ', recentPatients:'সাম্প্রতিক রোগী', todaysAppointments:'আজকের অ্যাপয়েন্টমেন্ট', viewAll:'সব দেখুন', start:'শুরু', view:'দেখুন', consult:'পরামর্শ', upcoming:'আসন্ন', confirmed:'নিশ্চিত', online:'অনলাইন', inClinic:'ক্লিনিকে', followUp:'ফলো-আপ', firstVisit:'প্রথম ভিজিট', reportDiscussion:'রিপোর্ট আলোচনা', recent:'সাম্প্রতিক', noData:'এখনও কোনো তথ্য নেই', connectBackend:'লাইভ ডেটা দেখাতে ডক্টর ড্যাশবোর্ড API সংযুক্ত করুন।', aiAsk:'MediMitra AI-কে জিজ্ঞাসা করুন', aiComing:'ক্লিনিক্যাল AI ইন্টারফেস প্রস্তুত। পরবর্তী ধাপে backend/RAG সংযুক্ত করা যাবে।',
  filter:'ফিল্টার', addPatient:'রোগী যোগ করুন', patientSearch:'নাম, ফোন বা ID দিয়ে রোগী খুঁজুন...', status:'স্ট্যাটাস', action:'অ্যাকশন', active:'সক্রিয়', inactive:'নিষ্ক্রিয়', id:'ID', name:'নাম', ageGender:'বয়স / লিঙ্গ', lastVisit:'শেষ ভিজিট',
  pendingTab:'অপেক্ষমাণ', cancelled:'বাতিল', day:'দিন', week:'সপ্তাহ', month:'মাস', addSlot:'স্লট যোগ করুন', availableSlots:'উপলভ্য সময়', manageSchedule:'আপনার সময় ও পরামর্শের সময়সূচি পরিচালনা করুন।',
  history:'ইতিহাস', notes:'নোট', chiefComplaint:'প্রধান অভিযোগ', diagnosis:'রোগ নির্ণয় (ঐচ্ছিক)', saveNotes:'নোট সংরক্ষণ', viewHistory:'ইতিহাস দেখুন', documents:'ডকুমেন্ট',
  newPrescription:'নতুন প্রেসক্রিপশন', prescriptionSearch:'প্রেসক্রিপশন খুঁজুন...', all:'সব', date:'তারিখ', medicines:'ওষুধ',
  medicalRecords:'মেডিকেল রেকর্ড', reports:'রিপোর্ট', notesTab:'নোট', others:'অন্যান্য', upload:'আপলোড',
  earningsReports:'আয় ও রিপোর্ট', totalEarnings:'মোট আয়', totalConsultations:'মোট পরামর্শ', onlineConsultations:'অনলাইন পরামর্শ', inClinicConsultations:'ক্লিনিক পরামর্শ', earningsOverview:'আয়ের সারাংশ', consultationTypes:'পরামর্শের ধরন',
  myProfile:'আমার প্রোফাইল', professionalInfo:'পেশাগত তথ্য', contactInfo:'যোগাযোগের তথ্য', changePhoto:'ছবি পরিবর্তন', editProfile:'প্রোফাইল সম্পাদনা', verified:'ভেরিফায়েড', registration:'রেজিস্ট্রেশন নম্বর', clinicAddress:'ক্লিনিক ঠিকানা', experience:'অভিজ্ঞতা',
  appearance:'অ্যাপিয়ারেন্স', light:'লাইট', dark:'ডার্ক', system:'সিস্টেম', language:'ভাষা', english:'English', bengali:'বাংলা', hindi:'हिन्दी', notificationsSettings:'নোটিফিকেশন', emailNotifications:'ইমেইল নোটিফিকেশন', appointmentAlerts:'অ্যাপয়েন্টমেন্ট অ্যালার্ট', newPatientRequests:'নতুন রোগীর অনুরোধ', security:'সিকিউরিটি', changePassword:'পাসওয়ার্ড পরিবর্তন', twoFactor:'টু-ফ্যাক্টর অথেনটিকেশন', account:'অ্যাকাউন্ট', deleteAccount:'অ্যাকাউন্ট মুছুন',
  aiTitle:'MediMitra AI সহকারী', aiSubtitle:'আপনার পেশাদার স্বাস্থ্য সহকারী।', hello:'হ্যালো! আমি MediMitra AI। আজ কীভাবে সাহায্য করতে পারি?', showPending:'আজকের অপেক্ষমাণ অ্যাপয়েন্টমেন্ট দেখাও।', aiReply:'আজ আপনার ৫টি অপেক্ষমাণ অ্যাপয়েন্টমেন্ট আছে। আমি রোগীর ইতিহাস সারাংশ, নোট সাজানো এবং কনসাল্টেশন ড্রাফটে সাহায্য করতে পারি।', typeMessage:'মেসেজ লিখুন...', send:'পাঠান',
  noDoctor:'ডাক্তার', notAvailable:'উপলভ্য নয়', menu:'মেনু', close:'বন্ধ',
};

const hi: Dict = {
  overview:'ओवरव्यू', appointments:'अपॉइंटमेंट', patients:'मरीज़', schedule:'मेरा शेड्यूल', consultations:'कंसल्टेशन', prescriptions:'प्रिस्क्रिप्शन', records:'मेडिकल रिकॉर्ड', earnings:'कमाई', profile:'प्रोफ़ाइल', settings:'सेटिंग्स', ai:'AI सहायक', logout:'लॉगआउट',
  search:'मरीज़, अपॉइंटमेंट खोजें...', notifications:'नोटिफिकेशन', type:'प्रकार', goodMorning:'सुप्रभात', welcome:'अपने प्रैक्टिस का सार देखें और बेहतर, स्मार्ट केयर दें।', totalPatients:'कुल मरीज़', todayAppointments:'आज के अपॉइंटमेंट', pendingRequests:'लंबित अनुरोध', totalPrescriptions:'कुल प्रिस्क्रिप्शन', thisMonth:'इस महीने', completed:'पूर्ण', pending:'लंबित', thisWeek:'इस सप्ताह', today:'आज', recentPatients:'हाल के मरीज़', todaysAppointments:'आज के अपॉइंटमेंट', viewAll:'सभी देखें', start:'शुरू', view:'देखें', consult:'कंसल्ट', upcoming:'आगामी', confirmed:'पुष्ट', online:'ऑनलाइन', inClinic:'क्लिनिक में', followUp:'फॉलो-अप', firstVisit:'पहली विज़िट', reportDiscussion:'रिपोर्ट चर्चा', recent:'हालिया', noData:'अभी कोई डेटा उपलब्ध नहीं', connectBackend:'लाइव डेटा के लिए डॉक्टर डैशबोर्ड API जोड़ें।', aiAsk:'MediMitra AI से पूछें', aiComing:'क्लिनिकल AI इंटरफेस तैयार है। अगले चरण में backend/RAG जोड़ा जा सकता है।',
  filter:'फ़िल्टर', addPatient:'मरीज़ जोड़ें', patientSearch:'नाम, फोन या ID से मरीज़ खोजें...', status:'स्थिति', action:'एक्शन', active:'सक्रिय', inactive:'निष्क्रिय', id:'ID', name:'नाम', ageGender:'उम्र / लिंग', lastVisit:'अंतिम विज़िट',
  pendingTab:'लंबित', cancelled:'रद्द', day:'दिन', week:'सप्ताह', month:'महीना', addSlot:'स्लॉट जोड़ें', availableSlots:'उपलब्ध समय', manageSchedule:'अपनी उपलब्धता और कंसल्टेशन शेड्यूल प्रबंधित करें।',
  history:'इतिहास', notes:'नोट्स', chiefComplaint:'मुख्य शिकायत', diagnosis:'निदान (वैकल्पिक)', saveNotes:'नोट्स सेव करें', viewHistory:'इतिहास देखें', documents:'दस्तावेज़',
  newPrescription:'नया प्रिस्क्रिप्शन', prescriptionSearch:'प्रिस्क्रिप्शन खोजें...', all:'सभी', date:'तारीख', medicines:'दवाएं',
  medicalRecords:'मेडिकल रिकॉर्ड', reports:'रिपोर्ट', notesTab:'नोट्स', others:'अन्य', upload:'अपलोड',
  earningsReports:'कमाई और रिपोर्ट', totalEarnings:'कुल कमाई', totalConsultations:'कुल कंसल्टेशन', onlineConsultations:'ऑनलाइन कंसल्टेशन', inClinicConsultations:'क्लिनिक कंसल्टेशन', earningsOverview:'कमाई का सार', consultationTypes:'कंसल्टेशन प्रकार',
  myProfile:'मेरी प्रोफ़ाइल', professionalInfo:'पेशेवर जानकारी', contactInfo:'संपर्क जानकारी', changePhoto:'फोटो बदलें', editProfile:'प्रोफ़ाइल संपादित करें', verified:'सत्यापित', registration:'रजिस्ट्रेशन नंबर', clinicAddress:'क्लिनिक पता', experience:'अनुभव',
  appearance:'दिखावट', light:'लाइट', dark:'डार्क', system:'सिस्टम', language:'भाषा', english:'English', bengali:'বাংলা', hindi:'हिन्दी', notificationsSettings:'नोटिफिकेशन', emailNotifications:'ईमेल नोटिफिकेशन', appointmentAlerts:'अपॉइंटमेंट अलर्ट', newPatientRequests:'नए मरीज़ अनुरोध', security:'सुरक्षा', changePassword:'पासवर्ड बदलें', twoFactor:'टू-फैक्टर ऑथेंटिकेशन', account:'अकाउंट', deleteAccount:'अकाउंट हटाएं',
  aiTitle:'MediMitra AI सहायक', aiSubtitle:'आपका प्रोफेशनल हेल्थ असिस्टेंट।', hello:'नमस्ते! मैं MediMitra AI हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?', showPending:'आज के लंबित अपॉइंटमेंट दिखाओ।', aiReply:'आज आपके 5 लंबित अपॉइंटमेंट हैं। मैं मरीज़ की हिस्ट्री का सार, नोट्स व्यवस्थित करने और कंसल्टेशन ड्राफ्ट में मदद कर सकता हूँ।', typeMessage:'अपना संदेश लिखें...', send:'भेजें',
  noDoctor:'डॉक्टर', notAvailable:'उपलब्ध नहीं', menu:'मेनू', close:'बंद',
};

export const doctorDashboardDictionaries: Record<LanguageCode, Dict> = { en, bn, hi };
